=== RVeraksa/Task_3/src/main/resources/germs.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="unqualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Gems">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Gem">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="Name"/>
                            <xs:element name="VisualParamets">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="Colour"/>
                                        <xs:element  name="Clarity">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="0"/>
                                                    <xs:maxInclusive value="100"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element  name="Border">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="4"/>
                                                    <xs:maxInclusive value="15"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:positiveInteger" name="Value"/>
                            <xs:element type="xs:string" name="Country"/>
                        </xs:sequence>
                        <xs:attribute  name="preciousness">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="precious"/>
                                    <xs:enumeration value="semiprecious"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RVeraksa/Task_3/src/main/resources/germs.xml
<?xml version="1.0" encoding="UTF-8"?>
<Gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="germs.xsd">
    <Gem preciousness="precious">
        <Name>
            Diamond
        </Name>
        <VisualParamets>
            <Colour>
                Clear
            </Colour>
            <Clarity>
                29
            </Clarity>
            <Border>
                10
            </Border>
        </VisualParamets>
        <Value>
            20
        </Value>
        <Country>
            Russia
        </Country>
    </Gem>
</Gems>
